<?php

// Do not edit this file. You have to edit config.php to establish database connection

require("../../config.php");
error_reporting(0);



// Create connection
$conn = mysqli_connect($servername, $username, $password, $database);
// Check connection
if (!$conn) {
      die("Connection failed: " . mysqli_connect_error());
}
 


$name= $_POST['txtName'];
$email= $_POST['txtEmail'];
$phone= $_POST['txtPhone'];
$message= $_POST['txtMsg'];

if (empty($name || $email || $phone || $message)) {
  echo "Fields can not be empty. You are being redirected.";
  header( "refresh:4;url=index.php" );
  exit(0);
  
  
}

$cleansedname= mysqli_real_escape_string($conn,$name);
$cleansedemail= mysqli_real_escape_string($conn,$email);
$cleansedphone= mysqli_real_escape_string($conn,$phone);
$cleansedmessage= mysqli_real_escape_string($conn,$message);
            

 
 $sql = "INSERT INTO contact (id,name, email, phone,message, date) VALUES ('','$cleansedname', '$cleansedemail', '$cleansedphone', '$cleansedmessage', NULL)";
if (mysqli_query($conn, $sql)) {
      echo "Your message has been sent successfully.";
	  echo "Your are being redirected.";
	  header( "refresh:5;url=index.php" );
} else {
      echo "An error occured! Try again later.";
}
mysqli_close($conn);  
?>